<?xml version="1.0" ?>
<robot name='robot' xmlns:xacro="http://ros.org/wiki/xacro">

    <xacro:include filename="$(find robot_description)/urdf/gazebo.urdf.xacro" />
    <xacro:include filename="$(find robot_description)/urdf/lidar.urdf.xacro" />
    <xacro:include filename="$(find robot_description)/urdf/depth.urdf.xacro" />
    

     <!-- Define robot constants -->
  <xacro:property name="base_width" value="0.31"/>
  <xacro:property name="base_length" value="0.42"/>
  <xacro:property name="base_height" value="0.18"/>

  <xacro:property name="wheel_radius" value="0.10"/>
  <xacro:property name="wheel_width" value="0.04"/>
  <xacro:property name="wheel_ygap" value="0.025"/>
  <xacro:property name="wheel_zoff" value="0.05"/>
  <xacro:property name="wheel_xoff" value="0.12"/>

  <xacro:property name="caster_xoff" value="0.14"/>

  <!-- Define intertial property macros  -->
  <xacro:macro name="box_inertia" params="m w h d">
    <inertial>
      <origin xyz="0 0 0" rpy="${pi/2} 0 ${pi/2}"/>
      <mass value="${m}"/>
      <inertia ixx="${(m/12) * (h*h + d*d)}" ixy="0.0" ixz="0.0" iyy="${(m/12) * (w*w + d*d)}" iyz="0.0" izz="${(m/12) * (w*w + h*h)}"/>
    </inertial>
  </xacro:macro>

  <xacro:macro name="cylinder_inertia" params="m r h">
    <inertial>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
      <mass value="${m}"/>
      <inertia ixx="${(m/12) * (3*r*r + h*h)}" ixy = "0" ixz = "0" iyy="${(m/12) * (3*r*r + h*h)}" iyz = "0" izz="${(m/2) * (r*r)}"/>
    </inertial>
  </xacro:macro>

  <xacro:macro name="sphere_inertia" params="m r">
    <inertial>
      <mass value="${m}"/>
      <inertia ixx="${(2/5) * m * (r*r)}" ixy="0.0" ixz="0.0" iyy="${(2/5) * m * (r*r)}" iyz="0.0" izz="${(2/5) * m * (r*r)}"/>
    </inertial>
  </xacro:macro>

  <!-- Robot Base -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="Black">
        <color rgba="0 0.0 0.0 1.0"/>
      </material>
    </visual>

        <collision>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>

    <xacro:box_inertia m="15" w="${base_width}" d="${base_length}" h="${base_height}"/>

  </link>

  <!-- Robot Footprint -->
  <link name="base_footprint"/>

  <joint name="base_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_footprint"/>
    <origin xyz="0.0 0.0 ${-(wheel_radius+wheel_zoff)}" rpy="0 0 0"/>
  </joint>

    <!-- Wheels -->
  <xacro:macro name="wheel" params="prefix x_reflect y_reflect">
    <link name="${prefix}_link">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="Grey1">
			<color rgba="0.2 0.1 0.0 1.0"/>
		</material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>

      <xacro:cylinder_inertia m="0.5" r="${wheel_radius}" h="${wheel_width}"/>

    </link>

    <joint name="${prefix}_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${prefix}_link"/>
      <origin xyz="${x_reflect*wheel_xoff} ${y_reflect*(base_width/2+wheel_ygap)} ${-wheel_zoff}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

  <xacro:wheel prefix="drivewhl_l" x_reflect="-1" y_reflect="1" />
  <xacro:wheel prefix="drivewhl_r" x_reflect="-1" y_reflect="-1" />

    <!-- Caster Wheel -->
  <link name="front_caster">
    <visual>
      <geometry>
        <sphere radius="${(wheel_radius+wheel_zoff-(base_height/2))}"/>
      </geometry>
      <material name="Grey1">
		<color rgba="0.2 0.1 0.0 1.0"/>
	  </material>
    </visual>
        <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="${(wheel_radius+wheel_zoff-(base_height/2))}"/>
      </geometry>
    </collision>

    <xacro:sphere_inertia m="0.5" r="${(wheel_radius+wheel_zoff-(base_height/2))}"/>
  </link>

  <joint name="caster_joint" type="continuous">
    <parent link="base_link"/>
    <child link="front_caster"/>
    <origin xyz="${caster_xoff} 0.0 ${-(base_height/2)}" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
  </joint>


  <link name="fara1_link">
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry>
				<box size="0.04 0.03 0.03"/>
			</geometry>
	     	<material name="Pink">
				<color rgba="1.0 1.0 0.0 1.0"/>
			</material>
	   </visual>
	</link>

	<joint name="fara1_joint" type="fixed">
    	<parent link="base_link"/>
    	<child link="fara1_link"/>
    	<origin xyz="0.20 0.0775 0.05" rpy="0 0 0"/>
	</joint>

	<link name="fara2_link">
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry>
				<box size="0.04 0.03 0.03"/>
			</geometry>
	     	<material name="Pink">
				<color rgba="1.0 1.0 0.0 1.0"/>
			</material>
	   </visual>
	</link>

	<joint name="fara2_joint" type="fixed">
    	<parent link="base_link"/>
    	<child link="fara2_link"/>
    	<origin xyz="0.20 -0.0775 0.05" rpy="0 0 0"/>
	</joint>
  
 	<link name="base_shape">
		<visual>
		    <origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry>
				<box size="0.32 0.32 0.32"/>
			</geometry>
			<material name="LightBrown">
	       		<color rgba="1 0.8 0.6 1.0"/>
	     	</material>
		</visual>	

    <collision>
      <geometry>
        <box size="${base_length} ${base_length} ${base_length}"/>
      </geometry>
    </collision>

    <xacro:box_inertia m="15" w="${base_length}" d="${base_length}" h="${base_length}"/>

	</link>
	
	<joint name="base_shape_joint" type="fixed">
    	<parent link="base_link"/>
   		<child link="base_shape"/>
    	<origin xyz="0.0 0.0 0.25" rpy="0 0 0"/>
  	</joint>

	<link name="right_ear_link">
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry>
				<box size="0.1 0.04 0.1"/>
			</geometry>
	     	<material name="Grey1">
				<color rgba="0.2 0.1 0.0 1.0"/>
			</material>
	   </visual>
	</link>

	<joint name="right_ear_joint" type="fixed">
    	<parent link="base_shape"/>
    	<child link="right_ear_link"/>
    	<origin xyz="0.09 0.18 0.11" rpy="0 0 0"/>
	</joint>
	
	<link name="left_ear_link">
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry>
				<box size="0.1 0.04 0.1"/>
			</geometry>
	     	<material name="Grey1">
				<color rgba="0.2 0.1 0.0 1.0"/>
			</material>
	   </visual>
	</link>

	<joint name="left_ear_joint" type="fixed">
    	<parent link="base_shape"/>
    	<child link="left_ear_link"/>
    	<origin xyz="0.09 -0.18 0.11" rpy="0 0 0"/>
	</joint>
	
	<link name="eye_link">
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry>
				<box size="0.03 0.23 0.04"/>
			</geometry>
	     	<material name="Black">
				<color rgba="0.0 0.0 0.0 1.0"/>
			</material>
	   </visual>
	</link>

	<joint name="eye_joint" type="fixed">
    	<parent link="base_shape"/>
    	<child link="eye_link"/>
    	<origin xyz="0.16 0.0 0.04" rpy="0 0 0"/>
	</joint>

	<link name="nose_link">
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry>
				<box size="0.05 0.14 0.08"/>
			</geometry>
	     	<material name="Black">
				<color rgba="0.0 0.0 0.0 1.0"/>
			</material>
	   </visual>
	</link>

	<joint name="nose_joint" type="fixed">
    	<parent link="base_shape"/>
    	<child link="nose_link"/>
    	<origin xyz="0.17 0.0 0.0" rpy="0 0 0"/>
	</joint>
	
	<link name="mouth_link">
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry>
				<box size="0.03 0.14 0.11"/>
			</geometry>
	     	<material name="light_gray">
				<color rgba="1 0.9 0.8 1.0"/>
			</material>
	   </visual>
	</link>

	<joint name="mouth_joint" type="fixed">
    	<parent link="base_shape"/>
    	<child link="mouth_link"/>
    	<origin xyz="0.16 0.0 -0.105" rpy="0 0 0"/>
	</joint>
	
	<link name="left_eye_link">
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry>
				<box size="0.01 0.045 0.042"/>
			</geometry>
	     	<material name="White">
				<color rgba="1.0 1.0 1.0 1.0"/>
			</material>
	   </visual>
	</link>

	<joint name="left_eye_joint" type="fixed">
    	<parent link="base_shape"/>
    	<child link="left_eye_link"/>
    	<origin xyz="0.16 0.0925 0.08" rpy="0 0 0"/>
	</joint>

	<link name="right_eye_link">
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry>
				<box size="0.01 0.045 0.042"/>
			</geometry>
	     	<material name="White">
				<color rgba="1.0 1.0 1.0 1.0"/>
			</material>
	   </visual>
	</link>

	<joint name="right_eye_joint" type="fixed">
    	<parent link="base_shape"/>
    	<child link="right_eye_link"/>
    	<origin xyz="0.16 -0.0925 0.08" rpy="0 0 0"/>
	</joint>
	

	<link name="left_e_link">
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry>
				<box size="0.01 0.045 0.038"/>
			</geometry>
	     	<material name="Black">
				<color rgba="0.0 0.0 0.0 1.0"/>
			</material>
	   </visual>
	</link>

	<joint name="left_e_joint" type="fixed">
    	<parent link="base_shape"/>
    	<child link="left_e_link"/>
    	<origin xyz="0.16 0.0475 0.075" rpy="0 0 0"/>
	</joint>

	<link name="right_e_link">
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry>
				<box size="0.01 0.045 0.038"/>
			</geometry>
	     	<material name="Black">
				<color rgba="0.0 0.0 0.0 1.0"/>
			</material>
	   </visual>
	</link>

	<joint name="right_e_joint" type="fixed">
    	<parent link="base_shape"/>
    	<child link="right_e_link"/>
    	<origin xyz="0.16 -0.0475 0.075" rpy="0 0 0"/>
	</joint>

</robot>